### ISSUE TITLE
New problems under XE3

### ISSUE THREAD

**Issue by Lorenzobiondi** [LaKraven/LKSL#105]
I do not know, maybe I'll be wrong something in XE3 package creation, but for me still does not compile under Delphi XE3.
In LKSL.Generics.Collections there are other positions that need to be modified with the new directive SUPPORTS_DISPOSEOF, and even changing those I find this error:

[dcc32 Error] LKSL.Generics.Collections.pas (2109): E2506 Method of parameterized type declared into interface section must not use local symbol 'CENTER_ADDITION'

into

TLKCenteredList <T> .GetCount

  and

[dcc32 Error] LKSL.Generics.Collections.pas (2599): E2250 There is no overloaded version of 'PreOrderWalk' that can be called with These arguments

Maybe it's better that I wait for a release with XE3 package included.

**Comment by LaKraven** [comment]
Will be producing the XE3, 4, 5 and 6 packages when I get home this evening... so will resolve all these issues at the same time.

**Comment by LaKraven** [comment]
Resolved in 2eebf4a
