### ISSUE TITLE
Specify a description for the packages

### ISSUE THREAD

**Issue by CWBudde** [LaKraven/LKSL#116]
While I was only looking at the XE7 packages so far, these lack a proper description. It's as easy as opening the project options for the package and specify a description at the tab 'description'.

Alternatively it should be satisfying to add
    {$DESCRIPTION 'LKSL Runtime Library'}
to the .dpk file.

This is helpful to better identify the packages in the Components->Packages menu (otherwise the full filename [with full path] is shown, which can be lengthy)

**Comment by LaKraven** [comment]
Resolved in b37798e
