### ISSUE TITLE
Get back up to speed on "Generics Redux"

### ISSUE THREAD

**Issue by LaKraven** [LaKraven/LKSL#120]
Because I'd forgotten what had been implemented in "Master" and what had been implemented in "GenericsRedux", I've merged "GenericsRedux" back into "Master" and need to sort out the mess.

Annoying, yes, but I've been out of action for so long that I genuinely cannot remember what has been implemented, and what remains outstanding.

For that reason, I'm going to sort things out one Generics Collection type at a time until "Redux" becomes the normal.

I ask that nobody use the "LKSL.Generics.CollectionsRedux" unit in any projects... it'll be disappearing in the near future as the types are integrated correctly into "LKSL.Generics.Collections"

**Comment by LK-Daniel** [comment]
Wow, Simon definitely lost track of this particular project.
Since this is superseded by Issue #128, I'm going to close this issue.
