### ISSUE TITLE
Replacing the LKSL with the "ADAPT" library

### ISSUE THREAD

**Issue by LK-Daniel** [LaKraven/LKSL#129]
Following lengthy discussions and planning sessions with @LK-Simon, I recently broke ground on a full replacement library for the LKSL, with a new name, a more solid foundation, and automated cross-compiler testing for not only Delphi, but also FreePascal.

This library is called "ADAPT", and is going to be opened up to the public shortly.

It addresses virtually all issues outstanding in the LKSL, along with other issues discovered in the rewriting process as-yet not listed on the LKSL. Adds new functionality and features, expands existing functionality and features, increases performance, reduces memory overhead (where possible) and is basically a _better version_ of the LKSL.

ADAPT stands for "ADvanced Asynchronous Programming Toolkit" (the acronym is a bit of a stretch, I know, but it does sound pretty cool). The mandate is pretty-much the same, but it corrects some fundamental architectural flaws in the original LKSL design while detaching the library from Simon's former business.

I've also updated the soon-to-be-published "AGE" game engine to use ADAPT instead of LKSL, and the process of amending existing projects to use ADAPT instead of the LKSL is somewhat simple (a refactoring exercise for the most part)

I am also co-developing the ADAPT SDK alongside the ADAPT library, and this vastly reduces the time it takes to produce a fully-functional, highly-optimized asynchronous (multi-threaded, event-driven) system (it automates a vast majority of the code production for you). For the moment the SDK is for Delphi as well as a "stand-alone" toolkit... with a Lazarus integration planned (I need to learn the ins and outs of producing Lazarus IDE packages).

Anyway, this issue is to let people know that this is happening, and the LKSL readme will be amended with a link to the ADAPT library as soon as it goes from private to public (need to ensure 100% of the LKSL features are reimplemented in ADAPT before making it public and deprecating the LKSL).

**Comment by cesarliws** [comment]
Hi Daniel,

Sounds great!

I'm looking forward to hearing from you.


Best regards,


Cesar Romero


Em seg, 14 de mar de 2016 às 11:18, Daniel Jackson <notifications@github.com>
escreveu:

> Following lengthy discussions and planning sessions with @LK-Simon
> <https://github.com/LK-Simon>, I recently broke ground on a full
> replacement library for the LKSL, with a new name, a more solid foundation,
> and automated cross-compiler testing for not only Delphi, but also
> FreePascal.
>
> This library is called "ADAPT", and is going to be opened up to the public
> shortly.
>
> It addresses virtually all issues outstanding in the LKSL, along with
> other issues discovered in the rewriting process as-yet not listed on the
> LKSL. Adds new functionality and features, expands existing functionality
> and features, increases performance, reduces memory overhead (where
> possible) and is basically a *better version* of the LKSL.
>
> ADAPT stands for "ADvanced Asynchronous Programming Toolkit" (the acronym
> is a bit of a stretch, I know, but it does sound pretty cool). The mandate
> is pretty-much the same, but it corrects some fundamental architectural
> flaws in the original LKSL design while detaching the library from Simon's
> former business.
>
> I've also updated the soon-to-be-published "AGE" game engine to use ADAPT
> instead of LKSL, and the process of amending existing projects to use ADAPT
> instead of the LKSL is somewhat simple (a refactoring exercise for the most
> part)
>
> I am also co-developing the ADAPT SDK alongside the ADAPT library, and
> this vastly reduces the time it takes to produce a fully-functional,
> highly-optimized asynchronous (multi-threaded, event-driven) system (it
> automates a vast majority of the code production for you). For the moment
> the SDK is for Delphi as well as a "stand-alone" toolkit... with a Lazarus
> integration planned (I need to learn the ins and outs of producing Lazarus
> IDE packages).
>
> Anyway, this issue is to let people know that this is happening, and the
> LKSL readme will be amended with a link to the ADAPT library as soon as it
> goes from private to public (need to ensure 100% of the LKSL features are
> reimplemented in ADAPT before making it public and deprecating the LKSL).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LaKraven/LKSL/issues/129>.
>
-- 
Atenciosamente,

Cesar Romero
