### ISSUE TITLE
TESTERS WANTED for ADAPT (LKSL Replacement Library)

### ISSUE THREAD

**Issue by LK-Daniel** [LaKraven/LKSL#130]
Hi all reading this,

I'm looking to assemble a small team of "Testers" for the ADAPT library (which is currently set to "private") to review the codebase and play around with test implementations prior to unleashing it as a public project.

Testers will also be given access to the private ADAPT SDK repository, to play with the automation toolkit before each significant feature is made available in the public repo.

Please leave a comment indicating your interest so I can send invitations to join the "ADAPT Testers" team.

**Comment by LK-Daniel** [comment]
More details of what "ADAPT" is can be found with issue #129

**Comment by cesarliws** [comment]
Hi Daniel,

Please add me to beta testing.

**Comment by JonRobertson** [comment]
Me too.  Thanks.

**Comment by mWaltari** [comment]
Interested in ADAPT, would love to take it for a spin

-tee-

**Comment by FrameworksDeveloper** [comment]
Hi Daniel -
Having been evaluating LKSL recently, I would appreciate being part of your new ADAPT test group.

**Comment by LK-Daniel** [comment]
All those whom have expressed an interest above thus far have been invited.

**Comment by IL2** [comment]
Me too please :)
I want to have a look at ADAPT without prior knowledge of LKSL and curios about ADAPT SDK.
Btw, will you start new ADAPT repo or continue LKSL?

**Comment by LK-Daniel** [comment]
@IL2 ADAPT is in an entirely new repository, and this LKSL repository will be "phased out".

It's just because the entire repository structure is so different, rebasing wouldn't really be a good idea.

**Comment by IL2** [comment]
Yep, I see, more on that in #127 #128 #129.

**Comment by JonRobertson** [comment]
> All those whom have expressed an interest above thus far have been invited.

How would we access the repository?  Is the ADAPT library stored in the LSK repository?

**Comment by IL2** [comment]
No, ADAPT is a separate private repo https://github.com/LaKraven/ADAPT
which is available after being invited by LK-Daniel or LK-Simon only.
As per title post expressing a wish to join ADAPT Testers is enough.

**Comment by LK-Daniel** [comment]
@JonRobertson as @IL2 has said, the ADAPT library is in its own private repository, which you can access with an invitation sent by myself or @LK-Simon (he won't be sending any as he's still tackling serious health issues at the moment).

In the near future, the ADAPT repository will be changed from "Private" to "Public". The testing period is just me hoping people will catch any problems (and make any fundamental suggestions, as they see fit) prior to opening it up to everyone and anyone.
Unlike Simon, I really don't want to be breaking interfaces on a public codebase (sorry @LK-Simon, but it's a really bad habit and you really need to stop doing that).

Are you wishing to be invited?

**Comment by LK-Daniel** [comment]
For those invited so far (and those to be invited between now and Sunday/Monday)... this weekend is going to see a huge boom in activity on the ADAPT library, and hopefully enough movement on the SDK to warrant adding the repo to the @LaKraven/adapt-testers group.

At the moment there is no "conversation" system provided on GitHub (that I know of, anyway) to provide updates to the testers group... so unless I find a more suitable platform, I'll continue to post updates such as this one on this "Issue" (for which I presume each participant then receives a notification e-mail).

My goal is to have 100% of the LKSL's "core features" reimplemented in ADAPT before the end of Sunday. Ambitious, but should be doable.

**Comment by mWaltari** [comment]
Breaking the API is always OK if the new one is better or more logical.

And many times is very hard to see into the future far enough...

-tee-

**Comment by LK-Daniel** [comment]
> Breaking the API is always OK if the new one is better or more logical. And many times is very hard to see into the future far enough...

That may be true, however a well-defined interface should be concise enough that it shouldn't really need to be changed. I know that's not *always* possible, but Simon breaks interfaces more often than I change my socks.

**Comment by LK-Daniel** [comment]
To be fair and balanced, though, he did have to go through the entire "discovery" process on designing and building the various systems in the LKSL... including migrating and refactoring all of that over from the AGE project.
I have the benefit of his previous efforts.

**Comment by mWaltari** [comment]
In other hand I loved to follow Simon's process, all major changes where
always fun and educational.

This is why I don't like demos, because you can't see the development
process. End result is not always that informative...

-tee-

**Comment by LK-Daniel** [comment]
I am definitely thankful that there's such a clear commit history on this repository, that's for sure. I've studied in great detail the "evolution" of the LKSL, where things like the Event Engine started and what direction they've gone in.
It's pretty difficult to try and pin a "final" design on something like this, but at the same time something so deeply tied in to an implementation *needs* a solid design.... certainly in terms of the interfaces other developers are consuming.

**Comment by UweRaabe** [comment]
Sorry for being late to the party, but if there happens to be an empty seat I would like to join as well.

**Comment by Gronfi** [comment]
Hi!
if possible would like to join as well.
At the beginnings of the event engine I colaborated a little with Simon, testing and with some ideas.

**Comment by LK-Daniel** [comment]
Sorry for the lack of updates the last week or so... I've been suffering with a nasty bug that's been doing the rounds here in England. Nasty cough, congestion, endless headache, fever and cold sweats, delirium etc.
Haven't had a good night's sleep in at LEAST a week. First time I've switched the computer on since Easter!

**Comment by IL2** [comment]
Please take your time to recover you need. Hopefully your flu will pass and go without consequences.
We are still here and don't go away :)

**Comment by LK-Daniel** [comment]
Okay, all those whom have requested access thus far have been invited. Still waiting on 4 (at this moment in time) invitations to be accepted.

**Comment by LK-Daniel** [comment]
2 pending invites awaiting reply. One of them is yours, @JonRobertson :)

**Comment by antonydanby** [comment]
Daniel I would love to have a look at this if you are still taking on testers

**Comment by LK-Daniel** [comment]
@antonydanby invite sent :)

**Comment by antonydanby** [comment]
Thanks !!! Will look at it on Monday, have a good weekend

**Comment by ByteJuggler** [comment]
Would be interested in looking at this if you're looking for more eyeballs...

**Comment by LK-Daniel** [comment]
@ByteJuggler invite sent :)

**Comment by gcarreno** [comment]
Hi @LK-Daniel, 
One of the things I was waiting for was the point when the whole LKSL would compile under Lazarus on a Ubuntu 16.04 x86-64.
Can I have a looksie on the ADAPT repo to check and report about it?
ATM I've just recompiled the latest GetLazarus.org and that means FPC 3.0.0 and Lazarus 1.7, if that helps.

Thanks.

**Comment by LK-Daniel** [comment]
Hi @gcarreno... sorry for my late reply. Work commitments have kept me overwhelmingly busy for the past month (lot of travel, in particular).

I've sent you an invite, and I have a HUGE backlog of commits to deal with for the ADAPT library as well (it's been about a month since I committed anything to GitHub at all).

Yes, it is absolutely critical that ADAPT work the same way under FPC/Lazarus as it does under Delphi. Like you, I intend to use it for Linux-based projects... so that's constantly one of my chief concerns.

**Comment by lastpost** [comment]
Hi @LK-Daniel 
Late 2015 I posted a question here (last post)
http://otapi.com/2014/10/23/threading-evolved-again-high-precision-thread-as-a-component/
Now I know why I never got an answer, hope he's getting better...
Then I found your initiative. Great!. But I wonder if you've read my post, It could be important.
I use the HighPrecisionThread under XE4 for WIN/OSX. WIN works great but OSX....
Anyone here that did something with the thread under OSX ?
Maybe I can join in here ?
Best. Jan

**Comment by joeparkerz** [comment]
Possible to get a beta permission? Thank you very much.

**Comment by LK-Daniel** [comment]
@lastpost and @joeparkerz - Invitations sent.

Lot more work being done today... including a FireMonkey demo for the High Precision Thread library (since Unit Tests aren't suitable for properly testing Threads)

I need to wrap up IN THE VERY LEAST the `IADLookupList` interface as well as `TADLookupList` and `TADLookupListTS` implementations *today*. This is so I can get the Event Engine reimplemented (a mammoth task in its own right) and release this library to the public ASAP.

**Comment by BBasile** [comment]
I'm interested to test for FPC under linux but I cant guarantee that it'll effectively do it.

**Comment by LK-Daniel** [comment]
I've been surprised by how much ground-up redevelopment I've had to do for ADAPT... but we're suuuuuuper close to making the library public now.

Would like to ask those that have been testing and checking out changes if you wouldn't mind sharing any thoughts you have at this stage on the ADAPT "Issues" page. Once the Event Engine is functioning, and I've extended Unit Test coverage to parts as-yet uncovered, I'll be releasing ADAPT to the public.

**Comment by gcarreno** [comment]
I've been a bit silent and distant because I feel there isn't much in the FPC side of things.

But that could just be my warped view due to not having tried any FPC compile yet.

I'll need to dig into this to give a better and most insightful appreciation of the state of thing in relation to FPC.

**Comment by MMihelic** [comment]
Hi LK-Daniel,

I am just starting evaluating LKS event engine on a simple project. As I am not a seasoned Delphi programmer, I most probably cannot provide you with any significant input, but you might appreciate another set of eyes when you are so close to the release. I might stumble onto something by sheer (bad ;) ) luck.

**Comment by DelphiMarkus** [comment]
Hi LK-Daniel,

I am interested to test your ADAPT Library on Android an iOS.
