### ISSUE TITLE
Reintroduce Demos

### ISSUE THREAD

**Issue by akhedrane** [LaKraven/LKSL#19]
Hi

i would thank you for this great job, but it will be nice to add some samples as quick start codes.

**Comment by LaKraven** [comment]
Yes, the demos are going to be reintroduced at the same time as merging the EventThreadPool branch back into the Master (trunk) :)

**Comment by LaKraven** [comment]
I've also begun adding articles to the Wiki (https://github.com/LaKraven/LKSL/wiki) showing how to use certain areas of the library.

**Comment by LaKraven** [comment]
This should be broken down into separate issues for each respective *Feature* of the LKSL, otherwise it can never be closed!
