### ISSUE TITLE
FreePascal Port

### ISSUE THREAD

**Issue by LaKraven** [LaKraven/LKSL#21]
Bring the FPC Port into line with the Delphi sources and release it.

**Comment by mWaltari** [comment]
Why not go for Trunk version (The 3.0.0 etc) it supports the Delphi like name spaces. and so. Still could have separate units, but I would not support 2.6.x anymore. I tried the FPCUP (https://bitbucket.org/reiniero/fpcup) and it nicely gives me the trunk version, at least on Windows, 64bit linux had some problems but those might be just an user erros (Most likely). I think the 3.0.0 branch has already been made, so release is closer than I thought. (I think they dropped some functionality from it)

That is the beauty of the Open Source compiler, you always can just upgrade your tools, don't need to dig your pockets or ask your boss for money first :D

**Comment by LaKraven** [comment]
At the moment, I want to keep it in step with the Lazarus release (because the upcoming SDK will integrate directly into the Lazarus IDE). I'm also of the belief that, for the moment, most people are still using FPC 2.6.x.

Switching the unit names back out to dotted namespaces is a fairly trivial change when Laz integrates FPC 3.0.0 though :)

**Comment by LaKraven** [comment]
Supreceded by #23
