### ISSUE TITLE
Android support - Some issues when compiling/running on Android.

### ISSUE THREAD

**Issue by carmas123** [LaKraven/LKSL#28]
Can your comp used with Android and AppMethod?

**Comment by LaKraven** [comment]
Every feature in the LKSL (which, keep in mind, at this time is still in relatively early development... so be careful if using in a production environment) is platform-independent.

The LKSL is compatible with AppMethod's Pascal compiler (which is the same compiler and RTL as Delphi anyway).

The LKSL's features (all of them) are used as critical backbone pieces of my game engine, which compiles, builds and runs on Win32, Win64, MacOS, iOS and Android.

In the very least, support for these platforms is a fundamental consideration for the ENTIRE LKSL (so far as the Delphi units go, anyway). At no point will support for these platforms be dropped!

As the FreePascal support becomes greater, Linux32, Linux64, and Linux ARM will also be key target platforms.

**Comment by carmas123** [comment]
Have you tried to compile a simpla Android application with LKSL Events?

**Comment by LaKraven** [comment]
You're right... a recent addition to TLKCriticalSection is specific to Windows. I was unaware of this (haven't done a build for non-Windows platforms this week)... it has been fixed in commit f5380d6d3e

**Comment by carmas123** [comment]
When I try to run my application I got this error:
Named synchronization objects not supported on this platform.

**Comment by LaKraven** [comment]
I'm looking into this now!

**Comment by LaKraven** [comment]
Okay, I've resolved that issue now! Thanks for letting me know!

I recently reinstalled Windows on here, and now XE7 (update 1) won't let me send a build over to any of my Android devices. Very annoying, still trying to figure out why.
