### ISSUE TITLE
Would anyone object if I remove the Stream Helpers?

### ISSUE THREAD

**Issue by LaKraven** [LaKraven/LKSL#79]
I'd like to remove the LKSL.Streams.Helpers.pas unit entirely from the LKSL.

It was a nice idea, but there are several reasons I'd like to remove it:
  - It doesn't work at all with FreePascal (because Generics works differently)
  - They are intended to work with `TStream`, which is no longer the primary Stream type being used by the LKSL (as `TLKStream` and its descendants are vastly superior and encapsulate the behaviour anyway)
  - It bloats the binary sizes... for fundamentally zero gain.

The decision will be made on Monday, April 20th. If there is no compelling case made to keep the unit around, it will be removed.

**Comment by gcarreno** [comment]
From what you are telling us, it makes perfect sense to eliminate it all together.
I vote Yay!

**Comment by LaKraven** [comment]
Removed in 6a4bedf
