### ISSUE TITLE
Can't compiling for XE3

### ISSUE THREAD

**Issue by Lorenzobiondi** [LaKraven/LKSL#98]
Sorry I don't know if this is the correct way to indicate this kind of issue!
I can't compile for XE3. I derived the package for XE3 from XE7 one, but I can't compile, the message is 
" undeclared identifier : DisposeOf"!
Is it possible to have a DELPHI XE3 package working version?

**Comment by LaKraven** [comment]
I'll provide an official XE3 set of packages shortly and make them available.

**Comment by LaKraven** [comment]
Oh and, yes.... this is the correct way to indicate this kind of issue :+1:

**Comment by LaKraven** [comment]
Just committed the source changes necessary to compile the LKSL on versions prior to XE4... this is in commit ccdb926

Your package should compile now, @Lorenzobiondi, but I still need to create and commit an XE3 package to this repository, which I will do when I am back at my own PC.

**Comment by Lorenzobiondi** [comment]
Ok, I'll test it tomorrow!
thanks for the prompt replay!

**Comment by LaKraven** [comment]
No worries! This library is my baby, and I'm keen to make sure it works for as many people who want to use it as is viable :)

**Comment by LaKraven** [comment]
The source compiles under XE3 now... see issue #99 where I need to add packages for XE3 (also #100, #101, #102 for XE4 to XE6)
